# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RXTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  pod 'Gifu', '~> 1.2'
  
  pod 'RxCocoa'
  pod 'RxBlocking'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'RxSwift'


  target 'RXTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RXTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
